openapi: 3.0.0
info:
  version: 1.0.0
  title: NFT Market
  description: Create NFTs with Artificial Intelligence
servers: 
  - url: https://nft-market-production.up.railway.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/user:
    post:
      description: Insert new User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: newUser
                password:
                  type: string
                  example: myPassword
      responses:
        '201':
          description: User created with success
        '400':
          description: Invalid request
          content: 
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  msg:
                    type: string
                    example: Erro ao cadastrar usuario
    get:
      description: Get list of all users
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                      example: adminUser
                    isAdmin:
                      type: boolean
                      example: true
                
        '401':
          description: Not authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: Not authorized
  /api/v1/ipfs:
    post:
      description: Upload to Pinata
      security: 
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: A brand new NFT title
                image:
                  type: string
                  example: www.myimages123.com/1
                name:
                  type: string
                  example: NFT number one
                attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      trait_type: 
                        type: string
                        example: Strenght
                      value:
                        type: string
                        example: 10
      responses:
        '201': 
          description: JSON create with success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      ipfsHash:
                        type: string
                        example: hasjdhasd8723jasdjkahs87923
  /api/v1/auth/login:
    post:
      description: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: my_username
                password:
                  type: string
                  example: my_password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request, wrong user or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  msg:
                    type: string
                    example: invalid user or password
  /api/v1/openai:
    post:
      description: create new image usind dall-e-2
      security: 
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  example: An old man in a boat
                size:
                  type: string
                  example: 512x512
      responses:
        '201':
          description: Image created with dall-e-2
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        example: www.openapimage.com/2
        '500':
          description: Error generating image
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  msg:
                    type: string
                    example: error generating image
      
              
          
                
              
                      
                  
          